### ISSUE TITLE
貢献する方法について

### ISSUE THREAD

**Issue by mimikun** [kotofurumiya/genshin-dict#1]
貢献方法を記載したドキュメントがないので、例えば単語追加などのプルリクエストを送ることが難しいです。
CONTRIBUTING.md といった貢献方法を記載したドキュメントを用意していただけますか？

**Comment by kotofurumiya** [comment]
ありがとうございます。検討してみます。

貢献手順についてはまとめられそうですが、
登録単語の採用基準がもとより一貫しているわけではない（その場のノリで考えている）ので、
最低限の基準を明記できるよう調整します。

**Comment by mimikun** [comment]
ありがとうございます。
いくつか加えてほしい単語があるのでお待ちしています。
