### ISSUE TITLE
単語重複について

### ISSUE THREAD

**Issue by yaakiyu** [kotofurumiya/genshin-dict#9]
Windows版で使わせていただいてます。
些細な事で申し訳ないのですが、登録した際にいくつかデータに重複があったようなので報告しておきます。
```
! 指定された単語は既に登録されています。
えりなす	エリナス	人名
! 指定された単語は既に登録されています。
さんごのみや	珊瑚宮	人名
! 指定された単語は既に登録されています。
なみしぶきのえら	波しぶきのエラ	名詞
```

**Comment by kotofurumiya** [comment]
報告ありがとうございます！

エリナスと珊瑚宮は地名と人名の両方にあるため重複しているようです。片方だけになるようにしておきます。
波しぶきのエラは純粋な重複ですね。こちらも直しておきます。

**Comment by kotofurumiya** [comment]
対応したのでclose
